import Foundation

enum GroceryCategorizer {

  // MARK: - Public

  static func categorize(_ ingredient: String) -> GroceryCategory {
    let text = ingredient.lowercased()

    // Check compound/specific keywords first to avoid partial matches
    for (keyword, category) in compoundKeywords {
      if text.contains(keyword) { return category }
    }

    for (keyword, category) in keywords {
      if text.contains(keyword) { return category }
    }

    return .other
  }

  static func grouped(_ items: [ShoppingListModel]) -> [GroceryCategory: [ShoppingListModel]] {
    Dictionary(grouping: items) { categorize($0.value) }
  }

  // MARK: - Compound Keywords (checked first — more specific)

  private static let compoundKeywords: [(String, GroceryCategory)] = [
    // Pantry items that contain meat/dairy/produce words
    ("chicken broth", .pantry),
    ("chicken stock", .pantry),
    ("beef broth", .pantry),
    ("beef stock", .pantry),
    ("bone broth", .pantry),
    ("vegetable broth", .pantry),
    ("vegetable stock", .pantry),
    ("fish sauce", .condiments),
    ("oyster sauce", .condiments),
    ("coconut milk", .pantry),
    ("coconut cream", .pantry),
    ("coconut oil", .pantry),
    ("coconut flour", .pantry),
    ("almond milk", .beverages),
    ("almond flour", .pantry),
    ("oat milk", .beverages),
    ("soy milk", .beverages),
    ("rice milk", .beverages),
    ("cashew milk", .beverages),
    ("condensed milk", .pantry),
    ("evaporated milk", .pantry),
    ("powdered milk", .pantry),
    ("dry milk", .pantry),
    ("cream cheese", .dairy),
    ("sour cream", .dairy),
    ("heavy cream", .dairy),
    ("whipped cream", .dairy),
    ("ice cream", .frozen),
    ("cream of mushroom", .pantry),
    ("cream of chicken", .pantry),
    ("cream of celery", .pantry),
    ("peanut butter", .pantry),
    ("almond butter", .pantry),
    ("cashew butter", .pantry),
    ("sunflower butter", .pantry),
    ("apple cider vinegar", .condiments),
    ("balsamic vinegar", .condiments),
    ("rice vinegar", .condiments),
    ("rice wine vinegar", .condiments),
    ("red wine vinegar", .condiments),
    ("white wine vinegar", .condiments),
    ("sherry vinegar", .condiments),
    ("white vinegar", .condiments),
    ("distilled vinegar", .condiments),
    ("tomato paste", .pantry),
    ("tomato sauce", .pantry),
    ("tomato puree", .pantry),
    ("canned tomato", .pantry),
    ("diced tomato", .pantry),
    ("crushed tomato", .pantry),
    ("stewed tomato", .pantry),
    ("sun dried tomato", .pantry),
    ("sundried tomato", .pantry),
    ("roasted tomato", .pantry),
    ("dried cranberr", .pantry),
    ("dried fruit", .pantry),
    ("dried apricot", .pantry),
    ("dried fig", .pantry),
    ("dried mango", .pantry),
    ("dried cherry", .pantry),
    ("dried date", .pantry),
    ("frozen vegetable", .frozen),
    ("frozen fruit", .frozen),
    ("frozen berr", .frozen),
    ("frozen pea", .frozen),
    ("frozen corn", .frozen),
    ("frozen spinach", .frozen),
    ("frozen shrimp", .frozen),
    ("frozen chicken", .frozen),
    ("frozen fish", .frozen),
    ("frozen pizza", .frozen),
    ("frozen dinner", .frozen),
    ("frozen waffle", .frozen),
    ("frozen fry", .frozen),
    ("frozen fries", .frozen),
    ("green onion", .produce),
    ("spring onion", .produce),
    ("red onion", .produce),
    ("yellow onion", .produce),
    ("white onion", .produce),
    ("green pepper", .produce),
    ("red pepper", .produce),
    ("yellow pepper", .produce),
    ("chili pepper", .produce),
    ("hot pepper", .produce),
    ("sesame oil", .condiments),
    ("olive oil", .pantry),
    ("vegetable oil", .pantry),
    ("canola oil", .pantry),
    ("avocado oil", .pantry),
    ("cooking spray", .pantry),
    ("cooking oil", .pantry),
    ("peanut oil", .pantry),
    ("grape seed oil", .pantry),
    ("grapeseed oil", .pantry),
    ("corn starch", .pantry),
    ("corn meal", .pantry),
    ("corn flour", .pantry),
    ("bread crumb", .pantry),
    ("breadcrumb", .pantry),
    ("panko", .pantry),
    ("cake mix", .pantry),
    ("brownie mix", .pantry),
    ("pancake mix", .pantry),
    ("pie crust", .pantry),
    ("pizza dough", .bakery),
    ("phyllo dough", .frozen),
    ("puff pastry", .frozen),
    ("soy sauce", .condiments),
    ("hoisin sauce", .condiments),
    ("steak sauce", .condiments),
    ("hot sauce", .condiments),
    ("bbq sauce", .condiments),
    ("barbecue sauce", .condiments),
    ("buffalo sauce", .condiments),
    ("enchilada sauce", .condiments),
    ("marinara sauce", .condiments),
    ("pasta sauce", .condiments),
    ("pizza sauce", .condiments),
    ("tartar sauce", .condiments),
    ("cocktail sauce", .condiments),
    ("teriyaki sauce", .condiments),
    ("chili sauce", .condiments),
    ("sweet chili sauce", .condiments),
    ("worcestershire sauce", .condiments),
    ("tahini", .condiments),
    ("black bean", .pantry),
    ("kidney bean", .pantry),
    ("pinto bean", .pantry),
    ("navy bean", .pantry),
    ("cannellini bean", .pantry),
    ("garbanzo bean", .pantry),
    ("lima bean", .pantry),
    ("refried bean", .pantry),
    ("baked bean", .pantry),
    ("green bean", .produce),
    ("string bean", .produce),
    ("wax bean", .produce),
    ("brown rice", .pantry),
    ("white rice", .pantry),
    ("jasmine rice", .pantry),
    ("basmati rice", .pantry),
    ("wild rice", .pantry),
    ("arborio rice", .pantry),
    ("rice noodle", .pantry),
    ("egg noodle", .pantry),
    ("ramen noodle", .pantry),
    ("udon noodle", .pantry),
    ("soba noodle", .pantry),
    ("lo mein", .pantry),
    ("chow mein", .pantry),
    ("angel hair", .pantry),
    ("red wine", .beverages),
    ("white wine", .beverages),
    ("cooking wine", .pantry),
    ("rice wine", .pantry),
    ("marsala wine", .pantry),
    ("mirin", .pantry),
    ("sake", .pantry),
  ]

  // MARK: - Single Keywords

  private static let keywords: [(String, GroceryCategory)] = [
    // Produce — Vegetables
    ("artichoke", .produce),
    ("arugula", .produce),
    ("asparagus", .produce),
    ("avocado", .produce),
    ("bean sprout", .produce),
    ("beet", .produce),
    ("bell pepper", .produce),
    ("bok choy", .produce),
    ("broccoli", .produce),
    ("broccolini", .produce),
    ("brussels sprout", .produce),
    ("cabbage", .produce),
    ("carrot", .produce),
    ("cauliflower", .produce),
    ("celery", .produce),
    ("chard", .produce),
    ("collard", .produce),
    ("corn", .produce),
    ("cucumber", .produce),
    ("daikon", .produce),
    ("edamame", .produce),
    ("eggplant", .produce),
    ("endive", .produce),
    ("escarole", .produce),
    ("fennel", .produce),
    ("garlic", .produce),
    ("ginger", .produce),
    ("jalapeno", .produce),
    ("jicama", .produce),
    ("kale", .produce),
    ("kohlrabi", .produce),
    ("leek", .produce),
    ("lettuce", .produce),
    ("mushroom", .produce),
    ("okra", .produce),
    ("olive", .produce),
    ("onion", .produce),
    ("parsnip", .produce),
    ("pea", .produce),
    ("pepper", .produce),
    ("plantain", .produce),
    ("potato", .produce),
    ("pumpkin", .produce),
    ("radicchio", .produce),
    ("radish", .produce),
    ("rapini", .produce),
    ("rhubarb", .produce),
    ("romaine", .produce),
    ("rutabaga", .produce),
    ("salad", .produce),
    ("scallion", .produce),
    ("shallot", .produce),
    ("snap pea", .produce),
    ("snow pea", .produce),
    ("spinach", .produce),
    ("sprout", .produce),
    ("squash", .produce),
    ("sweet potato", .produce),
    ("taro", .produce),
    ("tomatillo", .produce),
    ("tomato", .produce),
    ("turnip", .produce),
    ("watercress", .produce),
    ("yam", .produce),
    ("zucchini", .produce),

    // Produce — Fruits
    ("apple", .produce),
    ("apricot", .produce),
    ("banana", .produce),
    ("blackberr", .produce),
    ("blueberr", .produce),
    ("cantaloupe", .produce),
    ("cherr", .produce),
    ("clementine", .produce),
    ("coconut", .produce),
    ("cranberr", .produce),
    ("date", .produce),
    ("dragon fruit", .produce),
    ("fig", .produce),
    ("grapefruit", .produce),
    ("grape", .produce),
    ("guava", .produce),
    ("honeydew", .produce),
    ("kiwi", .produce),
    ("kumquat", .produce),
    ("lemon", .produce),
    ("lime", .produce),
    ("lychee", .produce),
    ("mandarin", .produce),
    ("mango", .produce),
    ("melon", .produce),
    ("nectarine", .produce),
    ("orange", .produce),
    ("papaya", .produce),
    ("passion fruit", .produce),
    ("peach", .produce),
    ("pear", .produce),
    ("persimmon", .produce),
    ("pineapple", .produce),
    ("plum", .produce),
    ("pomegranate", .produce),
    ("raspberr", .produce),
    ("starfruit", .produce),
    ("strawberr", .produce),
    ("tangerine", .produce),
    ("watermelon", .produce),
    ("berr", .produce),

    // Produce — Fresh Herbs
    ("basil", .produce),
    ("chive", .produce),
    ("cilantro", .produce),
    ("dill", .produce),
    ("lemongrass", .produce),
    ("mint", .produce),
    ("parsley", .produce),
    ("rosemary", .produce),
    ("tarragon", .produce),
    ("thyme", .produce),
    ("herb", .produce),

    // Dairy & Eggs
    ("butter", .dairy),
    ("buttermilk", .dairy),
    ("cheddar", .dairy),
    ("cheese", .dairy),
    ("colby", .dairy),
    ("cottage cheese", .dairy),
    ("cream", .dairy),
    ("creme fraiche", .dairy),
    ("custard", .dairy),
    ("egg", .dairy),
    ("feta", .dairy),
    ("ghee", .dairy),
    ("goat cheese", .dairy),
    ("gouda", .dairy),
    ("gruyere", .dairy),
    ("half and half", .dairy),
    ("heavy whipping", .dairy),
    ("jack cheese", .dairy),
    ("mascarpone", .dairy),
    ("milk", .dairy),
    ("monterey jack", .dairy),
    ("mozzarella", .dairy),
    ("muenster", .dairy),
    ("parmesan", .dairy),
    ("pecorino", .dairy),
    ("pepper jack", .dairy),
    ("provolone", .dairy),
    ("queso", .dairy),
    ("ricotta", .dairy),
    ("swiss cheese", .dairy),
    ("whey", .dairy),
    ("yogurt", .dairy),

    // Meat & Poultry
    ("bacon", .meat),
    ("beef", .meat),
    ("bison", .meat),
    ("bratwurst", .meat),
    ("bresaola", .meat),
    ("brisket", .meat),
    ("capicola", .meat),
    ("chicken", .meat),
    ("chorizo", .meat),
    ("corned beef", .meat),
    ("deli meat", .meat),
    ("duck", .meat),
    ("filet mignon", .meat),
    ("flank steak", .meat),
    ("goat", .meat),
    ("goose", .meat),
    ("ground beef", .meat),
    ("ground pork", .meat),
    ("ground turkey", .meat),
    ("guanciale", .meat),
    ("ham", .meat),
    ("hot dog", .meat),
    ("italian sausage", .meat),
    ("jerky", .meat),
    ("kielbasa", .meat),
    ("lamb", .meat),
    ("liver", .meat),
    ("loin", .meat),
    ("lunch meat", .meat),
    ("meatball", .meat),
    ("mortadella", .meat),
    ("pancetta", .meat),
    ("pastrami", .meat),
    ("pepperoni", .meat),
    ("pheasant", .meat),
    ("pork", .meat),
    ("poultry", .meat),
    ("prosciutto", .meat),
    ("quail", .meat),
    ("rabbit", .meat),
    ("rib eye", .meat),
    ("ribeye", .meat),
    ("roast", .meat),
    ("salami", .meat),
    ("sausage", .meat),
    ("sirloin", .meat),
    ("skirt steak", .meat),
    ("sopressata", .meat),
    ("spam", .meat),
    ("steak", .meat),
    ("strip steak", .meat),
    ("tenderloin", .meat),
    ("turkey", .meat),
    ("veal", .meat),
    ("venison", .meat),

    // Seafood
    ("anchov", .seafood),
    ("bass", .seafood),
    ("calamari", .seafood),
    ("catfish", .seafood),
    ("clam", .seafood),
    ("cod", .seafood),
    ("crab", .seafood),
    ("crawfish", .seafood),
    ("crayfish", .seafood),
    ("fish", .seafood),
    ("flounder", .seafood),
    ("grouper", .seafood),
    ("haddock", .seafood),
    ("halibut", .seafood),
    ("lobster", .seafood),
    ("mackerel", .seafood),
    ("mahi mahi", .seafood),
    ("mussel", .seafood),
    ("octopus", .seafood),
    ("oyster", .seafood),
    ("perch", .seafood),
    ("pollock", .seafood),
    ("prawn", .seafood),
    ("salmon", .seafood),
    ("sardine", .seafood),
    ("scallop", .seafood),
    ("sea bass", .seafood),
    ("shrimp", .seafood),
    ("snapper", .seafood),
    ("sole", .seafood),
    ("squid", .seafood),
    ("swordfish", .seafood),
    ("tilapia", .seafood),
    ("trout", .seafood),
    ("tuna", .seafood),
    ("walleye", .seafood),

    // Bakery & Bread
    ("bagel", .bakery),
    ("baguette", .bakery),
    ("bialy", .bakery),
    ("biscuit", .bakery),
    ("bread", .bakery),
    ("brioche", .bakery),
    ("bun", .bakery),
    ("challah", .bakery),
    ("ciabatta", .bakery),
    ("cornbread", .bakery),
    ("crescent roll", .bakery),
    ("croissant", .bakery),
    ("crouton", .bakery),
    ("dinner roll", .bakery),
    ("english muffin", .bakery),
    ("flatbread", .bakery),
    ("focaccia", .bakery),
    ("hamburger bun", .bakery),
    ("hot dog bun", .bakery),
    ("kaiser roll", .bakery),
    ("lavash", .bakery),
    ("matzo", .bakery),
    ("muffin", .bakery),
    ("naan", .bakery),
    ("pita", .bakery),
    ("pretzel", .bakery),
    ("pumpernickel", .bakery),
    ("roll", .bakery),
    ("rye bread", .bakery),
    ("scone", .bakery),
    ("sourdough", .bakery),
    ("texas toast", .bakery),
    ("tortilla", .bakery),
    ("wrap", .bakery),

    // Pantry — Grains & Pasta
    ("angel hair", .pantry),
    ("barley", .pantry),
    ("breadcrumb", .pantry),
    ("buckwheat", .pantry),
    ("bulgur", .pantry),
    ("couscous", .pantry),
    ("farro", .pantry),
    ("fettuccine", .pantry),
    ("fusilli", .pantry),
    ("gnocchi", .pantry),
    ("grits", .pantry),
    ("lasagna", .pantry),
    ("linguine", .pantry),
    ("lo mein", .pantry),
    ("macaroni", .pantry),
    ("millet", .pantry),
    ("noodle", .pantry),
    ("orzo", .pantry),
    ("panko", .pantry),
    ("pasta", .pantry),
    ("penne", .pantry),
    ("polenta", .pantry),
    ("quinoa", .pantry),
    ("ramen", .pantry),
    ("ravioli", .pantry),
    ("rice", .pantry),
    ("rigatoni", .pantry),
    ("rotini", .pantry),
    ("spaghetti", .pantry),
    ("tortellini", .pantry),
    ("vermicelli", .pantry),
    ("ziti", .pantry),

    // Pantry — Baking & Staples
    ("baking powder", .pantry),
    ("baking soda", .pantry),
    ("brown sugar", .pantry),
    ("cake flour", .pantry),
    ("chocolate chip", .pantry),
    ("chocolate", .pantry),
    ("cocoa", .pantry),
    ("confectioner", .pantry),
    ("corn syrup", .pantry),
    ("cornmeal", .pantry),
    ("cornstarch", .pantry),
    ("cream of tartar", .pantry),
    ("extract", .pantry),
    ("flour", .pantry),
    ("food coloring", .pantry),
    ("frosting", .pantry),
    ("gelatin", .pantry),
    ("icing", .pantry),
    ("marshmallow", .pantry),
    ("molasses", .pantry),
    ("powdered sugar", .pantry),
    ("shortening", .pantry),
    ("sprinkle", .pantry),
    ("sugar", .pantry),
    ("vanilla", .pantry),
    ("yeast", .pantry),

    // Pantry — Canned & Jarred
    ("bean", .pantry),
    ("bouillon", .pantry),
    ("broth", .pantry),
    ("canned", .pantry),
    ("chickpea", .pantry),
    ("chutney", .pantry),
    ("coconut", .pantry),
    ("hearts of palm", .pantry),
    ("hummus", .pantry),
    ("lentil", .pantry),
    ("olive", .pantry),
    ("pesto", .pantry),
    ("pickle", .pantry),
    ("roasted pepper", .pantry),
    ("salsa verde", .pantry),
    ("stock", .pantry),
    ("sun dried", .pantry),
    ("water chestnut", .pantry),

    // Pantry — Oils, Sweeteners & Misc
    ("agave", .pantry),
    ("honey", .pantry),
    ("jam", .pantry),
    ("jelly", .pantry),
    ("maple syrup", .pantry),
    ("marmalade", .pantry),
    ("miso", .pantry),
    ("oil", .pantry),
    ("preserves", .pantry),
    ("syrup", .pantry),
    ("vinegar", .pantry),

    // Pantry — Nuts, Seeds & Dried
    ("almond", .pantry),
    ("cashew", .pantry),
    ("chia seed", .pantry),
    ("flax", .pantry),
    ("hazelnut", .pantry),
    ("hemp seed", .pantry),
    ("macadamia", .pantry),
    ("nut", .pantry),
    ("pecan", .pantry),
    ("pine nut", .pantry),
    ("pistachio", .pantry),
    ("poppy seed", .pantry),
    ("pumpkin seed", .pantry),
    ("seed", .pantry),
    ("sesame seed", .pantry),
    ("sunflower seed", .pantry),
    ("walnut", .pantry),

    // Pantry — Snacks & Breakfast
    ("cereal", .pantry),
    ("chip", .pantry),
    ("cracker", .pantry),
    ("dried fruit", .pantry),
    ("granola", .pantry),
    ("oat", .pantry),
    ("oatmeal", .pantry),
    ("popcorn", .pantry),
    ("trail mix", .pantry),

    // Pantry — Other
    ("grain", .pantry),
    ("tofu", .pantry),
    ("tempeh", .pantry),
    ("seitan", .pantry),
    ("nutritional yeast", .pantry),
    ("protein powder", .pantry),
    ("collagen", .pantry),

    // Spices & Seasonings
    ("allspice", .spices),
    ("anise", .spices),
    ("basil dried", .spices),
    ("bay leaf", .spices),
    ("bay leaves", .spices),
    ("black pepper", .spices),
    ("caraway", .spices),
    ("cardamom", .spices),
    ("cayenne", .spices),
    ("celery salt", .spices),
    ("celery seed", .spices),
    ("chili flake", .spices),
    ("chili powder", .spices),
    ("chipotle powder", .spices),
    ("cinnamon", .spices),
    ("clove", .spices),
    ("coriander", .spices),
    ("cream of tartar", .spices),
    ("cumin", .spices),
    ("curry", .spices),
    ("dill seed", .spices),
    ("everything bagel", .spices),
    ("fennel seed", .spices),
    ("five spice", .spices),
    ("garam masala", .spices),
    ("garlic powder", .spices),
    ("garlic salt", .spices),
    ("ground ginger", .spices),
    ("herbs de provence", .spices),
    ("italian seasoning", .spices),
    ("jerk seasoning", .spices),
    ("lemon pepper", .spices),
    ("marjoram", .spices),
    ("msg", .spices),
    ("mustard powder", .spices),
    ("mustard seed", .spices),
    ("nutmeg", .spices),
    ("old bay", .spices),
    ("onion powder", .spices),
    ("onion salt", .spices),
    ("oregano", .spices),
    ("paprika", .spices),
    ("parsley dried", .spices),
    ("peppercorn", .spices),
    ("red pepper flake", .spices),
    ("rosemary dried", .spices),
    ("saffron", .spices),
    ("sage", .spices),
    ("salt", .spices),
    ("seasoning", .spices),
    ("smoked paprika", .spices),
    ("star anise", .spices),
    ("sumac", .spices),
    ("taco seasoning", .spices),
    ("thyme dried", .spices),
    ("turmeric", .spices),
    ("white pepper", .spices),
    ("za'atar", .spices),
    ("zaatar", .spices),

    // Condiments & Sauces
    ("aioli", .condiments),
    ("amino", .condiments),
    ("capers", .condiments),
    ("dijon", .condiments),
    ("dressing", .condiments),
    ("gochujang", .condiments),
    ("harissa", .condiments),
    ("horseradish", .condiments),
    ("ketchup", .condiments),
    ("marinade", .condiments),
    ("mayo", .condiments),
    ("mayonnaise", .condiments),
    ("mole", .condiments),
    ("mustard", .condiments),
    ("ponzu", .condiments),
    ("ranch", .condiments),
    ("relish", .condiments),
    ("remoulade", .condiments),
    ("salsa", .condiments),
    ("sambal", .condiments),
    ("sriracha", .condiments),
    ("tabasco", .condiments),
    ("vinaigrette", .condiments),
    ("wasabi", .condiments),
    ("worcestershire", .condiments),

    // Beverages
    ("beer", .beverages),
    ("bourbon", .beverages),
    ("brandy", .beverages),
    ("champagne", .beverages),
    ("cider", .beverages),
    ("club soda", .beverages),
    ("cocktail", .beverages),
    ("coffee", .beverages),
    ("cola", .beverages),
    ("espresso", .beverages),
    ("ginger ale", .beverages),
    ("gin", .beverages),
    ("juice", .beverages),
    ("kombucha", .beverages),
    ("lemonade", .beverages),
    ("liqueur", .beverages),
    ("rum", .beverages),
    ("seltzer", .beverages),
    ("smoothie", .beverages),
    ("soda", .beverages),
    ("sparkling water", .beverages),
    ("tea", .beverages),
    ("tequila", .beverages),
    ("tonic", .beverages),
    ("vodka", .beverages),
    ("water", .beverages),
    ("whiskey", .beverages),
    ("wine", .beverages),

    // Frozen
    ("frozen", .frozen),
  ]
}
